services:
  web:
    restart: always
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    build:
      dockerfile: "Dockerfile dev"
    ports:
      - "3000:3000"
  tests:
    build:
      context: .
      dockerfile: "Dockerfile dev"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command:
      - npm
      - run
      - test